### PR TITLE
Add Rails 5.1 support

### PR DESCRIPTION
**Pull request by ZenCocoon**

### CODE REVIEW

**Comment by JulienItard** [comment]
@ZenCocoon Are you sure we won't have to remove 4.2 support to have 5.1 ?

**Comment by ZenCocoon** [comment]
@JulienItard not sure but to find out. For sure we need to add this support for Rails 5.1

**Comment by Azdaroth** [comment]
@ZenCocoon That's gonna require some conditionals per version or dropping support for Rails < 5

**Comment by ZenCocoon** [comment]
I think dropping support for Rails < 5 is ok.

**Comment by JulienItard** [comment]
Then we had to update every app and core first to 5.0

**Comment by ZenCocoon** [comment]
@JulienItard we will get there for sure, but we can still manage two branches in case of security issue, anyway all apps should get their now.

**Review by Azdaroth — APPROVED** [review]
💪

**Pull request merged**
